#!/usr/bin/env python3
"""
Ransomware Rhapsody (C21) — ZIP password cracker for W3_WANT_Y0U.zip
 
The zip is protected with a password generated by init_challenge.py:
  1. Pick 3 random words from a L33T word pool (with possible repeats)
  2. Shuffle them
  3. Randomize casing of every alpha character
 
This solver exhaustively enumerates ALL possible passwords by:
  - Trying all 11^3 = 1,331 word combinations
  - For each combo, trying all 2^N casing variants (N = number of alpha chars)
  - Total search space: ~5.45 million passwords
  - Expected runtime: 5-30 minutes depending on hardware
 
Usage:
    python3 zip_solver.py /path/to/W3_WANT_Y0U.zip
    python3 zip_solver.py -z /path/to/W3_WANT_Y0U.zip
"""
 
import argparse
import itertools
import sys
import time
import zipfile
 
# Exact word pool from init_challenge.py — all 11 words
WORD_POOL = [
    "w3", "we", "are", "4r3", "ar3", "th3", "the",
    "w4nt3d", "wanted", "w4nted", "want3d",
]
 
 
def casing_variants(base: str):
    """
    Yield every possible upper/lower casing of a string.
    Non-alpha characters (digits, spaces) pass through unchanged.
    For a string with N alpha characters, yields 2^N variants.
    """
    # Find positions of alpha characters
    alpha_positions = [i for i, c in enumerate(base) if c.isalpha()]
    n = len(alpha_positions)
 
    if n == 0:
        yield base
        return
 
    chars = list(base)
    for mask in range(1 << n):
        for bit_idx, pos in enumerate(alpha_positions):
            if mask & (1 << bit_idx):
                chars[pos] = base[pos].upper()
            else:
                chars[pos] = base[pos].lower()
        yield "".join(chars)
 
 
def generate_all_passwords():
    """
    Generator that yields every possible password.
    Matches init_challenge.py logic:
      - 3 words chosen from WORD_POOL (with replacement, all orderings)
      - Random casing applied to each alpha character
    """
    for w1, w2, w3 in itertools.product(WORD_POOL, repeat=3):
        base = f"{w1} {w2} {w3}"
        yield from casing_variants(base)
 
 
def crack_zip(zip_path: str) -> str | None:
    """
    Try every possible password against the zip file.
    Returns the password on success, None on failure.
    """
    # Pre-calculate total for progress reporting
    total = sum(
        2 ** sum(1 for c in f"{w1} {w2} {w3}" if c.isalpha())
        for w1, w2, w3 in itertools.product(WORD_POOL, repeat=3)
    )
 
    print(f"[*] Total passwords to try: {total:,}")
    print(f"[*] Opening {zip_path}")
 
    with zipfile.ZipFile(zip_path, "r") as zf:
        # Pick the first (usually only) file in the archive to test against
        test_name = zf.namelist()[0]
        print(f"[*] Testing against archive member: {test_name}")
        print()
 
        tried = 0
        start = time.time()
        last_report = start
 
        for password in generate_all_passwords():
            tried += 1
            pwd_bytes = password.encode("utf-8")
 
            try:
                # Read just one file to test — much faster than extractall
                zf.read(test_name, pwd=pwd_bytes)
                elapsed = time.time() - start
                print(f"\r\033[K", end="")
                print(f"✅ PASSWORD FOUND after {tried:,} attempts ({elapsed:.1f}s)")
                print(f"   Password: {password}")
                print(f"   Speed: {tried / elapsed:,.0f} passwords/sec")
                return password
            except (RuntimeError, zipfile.BadZipFile, Exception):
                pass
 
            # Progress report every 5 seconds
            now = time.time()
            if now - last_report >= 5.0:
                elapsed = now - start
                rate = tried / elapsed if elapsed > 0 else 0
                pct = tried / total * 100
                eta = (total - tried) / rate if rate > 0 else 0
                print(
                    f"\r  [{pct:5.1f}%] {tried:>8,} / {total:,}  "
                    f"| {rate:,.0f} pwd/s | ETA {eta / 60:.1f} min",
                    end="",
                    flush=True,
                )
                last_report = now
 
    elapsed = time.time() - start
    print(f"\r\033[K", end="")
    print(f"❌ FAILED — exhausted all {tried:,} passwords in {elapsed:.1f}s")
    return None
 
 
def main():
    parser = argparse.ArgumentParser(
        description="Crack the W3_WANT_Y0U.zip password (Ransomware Rhapsody C21)"
    )
    parser.add_argument(
        "zipfile",
        nargs="?",
        help="Path to the target ZIP file",
    )
    parser.add_argument(
        "-z", "--zip",
        dest="zipfile_alt",
        help="Path to the target ZIP file (alternate flag)",
    )
    args = parser.parse_args()
 
    zip_path = args.zipfile or args.zipfile_alt
    if not zip_path:
        parser.error("Please provide a path to the ZIP file")
 
    print("=" * 60)
    print("  Ransomware Rhapsody — ZIP Password Cracker")
    print("=" * 60)
    print()
 
    password = crack_zip(zip_path)
 
    if password:
        print()
        print(f"[+] Now extract with:")
        print(f"    unzip -P '{password}' {zip_path}")
        print()
 
        # Also try to extract automatically
        try:
            with zipfile.ZipFile(zip_path, "r") as zf:
                zf.extractall(pwd=password.encode("utf-8"))
                print(f"[+] Auto-extracted to current directory!")
                for name in zf.namelist():
                    print(f"    -> {name}")
        except Exception as e:
            print(f"[!] Auto-extract failed: {e}")
            print(f"    Use the manual command above.")
    else:
        print()
        print("[!] This should not happen — the search space is exhaustive.")
        print("[!] The zip may have been created with a different password scheme.")
        sys.exit(1)
 
 
if __name__ == "__main__":
    main()

