x-challenge:
  name: "WWW (Weak Web Warnings)"
  icon: TbWorldWww
  summary: >
    A small business developed a simple web server to consolidate their security alerts.
    Despite being a simple website, it's riddled with vulnerabilities with some not-so-simple
    caveats. You'll need to be clever to exploit them successfully. Can you find them all?
  description: |
    **NICE Work Roles**

    - [Exploitation Analysis](https://niccs.cisa.gov/workforce-development/nice-framework/)
    - [Vulnerability Analysis](https://niccs.cisa.gov/workforce-development/nice-framework/)

    **NICE Tasks**

    - [T1091](https://niccs.cisa.gov/workforce-development/nice-framework/): Perform authorized penetration testing on enterprise network assets.
    - [T1118](https://niccs.cisa.gov/workforce-development/nice-framework/): Identify vulnerabilities.

    ## Background

    Use the provided Kali machine to investigate and exploit `web.pccc`, a simple (and terribly insecure) tracker for security alerts.

    ## Getting Started

    The `web.pccc` server only offers two simple features: tracking security alerts and/or events, and listing the hosts and credentials for the business.

    ## Submission

    There are 4 tokens to retrieve in this challenge. Tokens 1, 2, and 4 follow the standard `PCCC{...}` format; Token 3 is a 12-character hexadecimal string.

    - Token 1: Retrieve the token found in a comment in the source code of the website.
    - Token 2: Successfully make a request for the `token.php` page; the token will be printed at the top of every page after `token.php` is executed.
    - Token 3: Retrieve the token stored in the website's database (table `Token`, column `Token`).
    - Token 4: Retrieve the token stored in the application's environment variables.

    ## System and Tool Credentials

    |system/tool|username|password|
    |-----------|--------|--------|
    |kali-weakweb|user|password|

    ## Note

    Attacking or unauthorized access to `challenge.pccc` is forbidden. You may only use the provided web page to view challenge progress and download any challenge artifacts that are provided.
  tags:
    - season:pc6
    - track:teams
    - round:finals
    - role:exploitation-analyst
    - role:vulnerability-analysis
    - topics:web
  variables:
    tokenSource:
      template: fake.hexify('PCCC{^^^^^^^^^^^^}')
      default: &tokenSource 'PCCC{500225e50125}'
    tokenProxy:
      template: fake.hexify('PCCC{^^^^^^^^^^^^}')
      default: &tokenProxy 'PCCC{9209a9209209}'
    tokenSQL:
      template: fake.hexify('^^^^^^^^^^^^')
      default: &tokenSQL '5009150091ab'
    tokenSerial:
      template: fake.hexify('PCCC{^^^^^^^^^^^^}')
      default: &tokenSerial 'PCCC{5e71a15e71a1}'
  questions:
    - name: "Token 1 - Source Comment"
      body: "Retrieve the token found in a comment in the source code of the website."
      points: 680
      answer: *tokenSource
      max_attempts: 100
      placeholder: "PCCC{############}"
    - name: "Token 2 - token.php"
      body: "Make a request for `token.php`; the token is printed at the top of every page after it executes."
      points: 680
      answer: *tokenProxy
      max_attempts: 100
      placeholder: "PCCC{############}"
    - name: "Token 3 - Database"
      body: "Retrieve the token stored in the website's database (table `Token`, column `Token`). This token is a 12-character hexadecimal string (no `PCCC{...}` wrapper)."
      points: 1020
      answer: *tokenSQL
      max_attempts: 100
      placeholder: "############"
    - name: "Token 4 - Environment"
      body: "Retrieve the token stored in the application's environment variables."
      points: 1020
      answer: *tokenSerial
      max_attempts: 100
      placeholder: "PCCC{############}"

services:
  proxy:
    build:
      context: ./website/proxy
    hostname: web.pccc
    networks:
      - competitor_net
      - web-network
  web:
    build:
      context: ./website/web
    hostname: web
    environment:
      token: *tokenSerial
      tokenProxy: *tokenProxy
      tokenSource: *tokenSource
    networks:
      - web-network
  db:
    build:
      context: ./website/db
    hostname: db
    mem_limit: 1g
    command:
      - "/usr/local/bin/mysqld.sh"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: web_alerts
      tokenSQL: *tokenSQL
    networks:
      - web-network
  challengeserver:
    build: ../../../../challenge-server
    hostname: challenge.pccc
    cap_add:
      - NET_ADMIN
    environment:
      pc_year: "6"
      challenge_name: "Weak Web Warnings"
    networks:
      - competitor_net

networks:
  competitor_net:
    internal: true
  web-network:
    internal: true
