x-challenge:
  name: "Ransomware Rhapsody"
  description: |
    # Ransomware Rhapsody

    In this challenge, challengers have stumbled upon a compromised system
    containing a collection of encrypted files. The adversary, in a bashful
    and hasty fashion, made a critical error on their exit. Your mission is
    to investigate the remnants of their work and let them know you're on to them.

    **NICE Work Roles**
    * [Digital Forensics](https://niccs.cisa.gov/workforce-development/nice-framework/work-role/digital-forensics)
    * [Incident Response](https://niccs.cisa.gov/workforce-development/nice-framework/work-role/incident-response)
    * [Exploitation Analysis](https://niccs.cisa.gov/workforce-development/nice-framework/work-role/exploitation-analysis)

    **NICE Tasks**
    * [T0108](https://niccs.cisa.gov/workforce-development/nice-framework/): Perform analysis of the incident to identify the affected systems, networks, and potential perpetrators.
    * [T0115](https://niccs.cisa.gov/workforce-development/nice-framework/): Analyze collected information to identify vulnerabilities and leverage them to achieve objectives.

    ## Background
    A crime syndicate called "The w4Nt3D" has infiltrated a corporate network.
    The asset challengers will have access to has been isolated and acts as the
    only point of access for triage.

    As a Rapid Response Team (RRT), you and a team of incident responders and
    threat hunters are tasked to:
    * Investigate the compromised system for encrypted corporate files
    * Decrypt the associated files using any discovered encryption key sets
    * Investigate the decrypted files to find a key used to communicate with the W4nt3D
    * Execute the beacon to let them know you're on to them

    ## Getting Started

    SSH into `corp-ubus-24lap` with the credentials below to begin.

    ## System and Tool Credentials

    | System               | OS          | Username | Password |
    |----------------------|-------------|----------|----------|
    | corp-ubus-24lap      | Ubuntu 22.04| user     | tartans  |

    ## Intelligence Brief

    The Intelligence Community (IC) has recently released a light version of a
    dossier on "The w4Nt3D". Details below:

    | Category               | Data |
    |------------------------|------|
    | **Leader**             | xCh4$3x |
    | **Known Members**      | 36 |
    | **Last Known Location**| Paris, France |
    | **Tactics**            | The syndicate involved with this cyber event is named "The w4Nt3D". Be on the look out for any artifacts or references to this. They are notorious for hiding their payloads and malware in plain sight for the thrill of being chased by authorities and to mock their victims. They tend to play games with their victims in order to illicit a response from them. |
    | **Signature**          | This syndicate has a tendency to put short form variants of their name in critical files on their victim's machines. |
    | **Slogans**            | In primary communications, they often use slogans and "L33T Speak". |

    ## Tactics, Techniques and Procedures
    * This syndicate will occasionally concatenate stolen tokens to create a master key that operators can use to `call home`.

    **[IMPORTANT] NOTE**
    Attacking or unauthorized access to the challenge server is **forbidden**.
    The `deployer` user is **not in scope** for this engagement.
    To complete this challenge, root is not required.

  icon: "TbSkull"
  summary: >-
    A crime syndicate called "The w4Nt3D" has infiltrated a corporate network.
    Investigate the compromised system, decrypt ransomed files, and call home
    to let the adversary know you're on to them.
  tags:
    - season:pc6
    - track:teams
    - round:finals
    - role:incident-response
    - role:forensics
    - role:exploitation-analyst
    - topics:forensics
    - topics:cryptography

  variables:
    TOKEN1:
      template: "fake.hexify('^^^^^^^^^^^^')"
      default: &TOKEN1 "a1bd34d4e5f6"
    TOKEN2:
      template: "fake.hexify('^^^^^^^^^^^^')"
      default: &TOKEN2 "b2d34dd4e5f6"
    TOKEN3:
      template: "fake.hexify('^^^^^^^^^^^^')"
      default: &TOKEN3 "c2d34dd4e5f6"
    TOKEN4:
      template: "fake.bothify('PCCC{0D-04-####-????}')"
      default: &TOKEN4 "PCCC{0E-02-RR4-FFB981}"

  questions:
    - name: "Question 1"
      body: "What is the name of the directory (folder only) which contains the encrypted corporate files?"
      placeholder: "[12 characters]"
      answer: *TOKEN1
      points: 555
      max_attempts: 100

    - name: "Question 2"
      body: "What are the first 12 characters of the AES IV value for decrypting the encrypted corporate files? (numerical values only e.g. ABCD1234)"
      placeholder: "[12 characters]"
      answer: *TOKEN2
      points: 1665
      max_attempts: 100

    - name: "Question 3"
      body: "After decryption of the files, what password was discovered for the service user?"
      placeholder: "[12 characters]"
      answer: *TOKEN3
      points: 925
      max_attempts: 100

    - name: "Question 4"
      body: "After your call with an important person, what is the final token the syndicate has left you?"
      placeholder: "PCCC{XXX-XXXXXX}"
      answer: *TOKEN4
      points: 555
      max_attempts: 100

services:
  challengeserver:
    image: 253388214223.dkr.ecr.us-east-1.amazonaws.com/pc7/challenge-server
    hostname: challenge.pccc
    networks:
      - competitor_net
      - platform_net
#    cap_add:
#      - NET_RAW
#      - NET_ADMIN
    environment:
      pc_year: "6"
      challenge_name: "Ransomware Rhapsody"

  corp-ubus-24lap:
    build:
      context: ./corp-ubus-24lap
      dockerfile: Dockerfile
    image: 253388214223.dkr.ecr.us-east-1.amazonaws.com/pc6/c22-ransomware-rhapsody_corp-ubus-24lap:latest
    hostname: corp-ubus-24lap
    environment:
      TOKEN1: *TOKEN1
      TOKEN2: *TOKEN2
      TOKEN3: *TOKEN3
      TOKEN4: *TOKEN4
    networks:
      - competitor_net
    cap_add:
      - SYS_PTRACE

networks:
  platform_net:
  competitor_net:
    internal: true